version: '3'
services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_PRO_MODEL=${GEMINI_PRO_MODEL}
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
